# Change these first
owner: hybridlights # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: main site (hybridlights.nl)
    url: https://www.hybridlights.nl
  - name: dev site
    url: https://hybridlights.timoo-dev.nl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
